export const texts = {
  brand: {
    name: "Play",
    tagline: "Sarcasm-fueled trivia arena.",
    punchline: "Play",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Challenges", href: "/challenge" },
    { label: "Leaderboard", href: "/leaderboard" },
  ],
  toasts: {
    correct: "Lucky guess, admit it.",
    wrong: "Oof. Not even close, but we admire the confidence.",
    timeout: "You blinked. That's on you.",
    achievement: "Congrats, you did something!",
  },
  home: {
    hero: {
      eyebrow: "Live challenge queue",
      title: "Think you're smart? Prove it. Or at least try.",
      description:
        "Micro challenges, zero chill copy, and dopamine hits faster than your Wi-Fi router drops packets.",
      primaryCta: "Play Now — before your brain cools off.",
      secondaryCta: "Browse Challenges",
      stats: [
        { label: "Brains roasted", value: "12,487", helper: "today alone" },
        { label: "Perfect streaks", value: "37", helper: "show-offs" },
        { label: "Avg. ego meter", value: "6.2/10", helper: "room to fall" },
      ],
    },
    featured: {
      title: "Featured challenges",
      subtitle: "Fresh drops with more attitude than your group chat.",
    },
    leaderboardPreview: {
      title: "Hall of Fame (and occasional shame).",
      subtitle: "These legends answered faster than you can Google.",
    },
  },
  challenge: {
    timerLabel: "Time left",
    scoreLabel: "Score",
    progressLabel: "Progress",
    egoMeter: (score) => `Ego Meter: ${score}/10 💅`,
    prompt: "Next Victim — I mean, Challenge.",
    prompts: [
      "Next Victim — I mean, Challenge.",
      "This one's got your name on it.",
      "Queue the smug applause.",
      "Fresh dose of digital ego.",
      "Trivia is served, sans mercy.",
      "Brain cells, assemble.",
      "Eyes on the buzzer.",
      "No sleep, just questions.",
      "Heightened panic incoming.",
      "Cue the dramatic music.",
      "Focus now, brag later.",
      "Where the brave collide.",
      "Time to flex on pixels.",
      "Pick your truth serum.",
      "This card doesn't bluff.",
      "Sweat optional, glory guaranteed.",
      "Hold tight, knowledge drop incoming.",
      "Serious vibes, not serious.",
      "Ready your typing fingers.",
      "This one comes with sass.",
      "Think fast, or think funny.",
      "A new thrill, same brain.",
      "Challenge queued, confidence optional.",
      "No time for second guessing.",
      "Let the shaming begin.",
      "Instant regret in 3...2...1.",
      "Caffeine anxious? good.",
      "Better hope you remembered that obscure fact.",
      "This will make your notifications jealous.",
      "Fortune favors the quick.",
      "Brains, meet pressure.",
      "Sass level: archived internet troll.",
      "If you win, we believe you.",
      "If you lose, we still clap.",
      "Another round of chaos sauce.",
      "We reroute this to your ego.",
      "The algorithm demands answers.",
      "Keep calm and pretend to know.",
      "Make some friends with the timer.",
      "Think of it as therapy, but louder.",
      "Victory tastes like leftover pizza.",
      "Laptop? ready. Ego? maybe.",
      "We message you from the future.",
      "This challenge runs on sarcasm.",
      "Confidence? start with that.",
      "Plug in, zone out, win.",
      "It's like your group chat, but fair.",
      "Streaks love this energy.",
      "A quirky question to break monotony.",
      "Answers served with a side of shade.",
      "Set your cursor on fire.",
      "Trivia with a witty smirk.",
      "You vs the timer. Deal?",
      "Spicy brain soup coming up.",
      "Dial-in, focus, conquer.",
      "Need more caffeine? good.",
      "Bring your own sass.",
      "Awkward silence about to be broken.",
      "This card is a mic drop.",
      "Confidence meter: adjust.",
      "Brag AND behave.",
      "We saved the spicy ones for you.",
      "Roast the question, not yourself.",
      "One tap, infinite regret.",
      "Your next brag, minutes away.",
      "Questions curated by chaos.",
      "Let the scoreboard tremble.",
      "This is not for the faint.",
      "Heads up! There’s a twist.",
      "Minimal chill, max meme.",
      "You're about to impress the void.",
      "Lightning round, with sparks.",
      "This question has a mood.",
      "Tune your brain for shock.",
      "Double-check your answer, or don't.",
      "No rewinds, only flexes.",
      "Timer is watching you.",
      "Your nerves just got a job.",
      "Ready to leave your mark?",
      "We wrote this to make you think twice.",
      "This is the spicy one you asked for.",
      "Elegance is answering quickly.",
      "We hope you like surprises.",
      "You can conquer this with sass.",
      "The scoreboard called, it wants you.",
      "One more question to dominate.",
      "This is the moment Larry from accounting envies.",
      "No, this isn't a drill.",
      "Please insert brain.",
      "Victory is a tap away.",
      "We just made your next distraction.",
      "This challenge keeps receipts.",
      "Your future self thanks you.",
      "Focus, because we are watching.",
      "This card is the drama llama.",
      "That's right, it's your turn.",
      "You got this. Probably.",
      "Populate the scoreboard with your name.",
      "Serious bragging rights locked here.",
      "Savage, witty, unstoppable.",
    ],
    emptyState: "Loading a fiendish puzzle...",
  },
  results: {
    heading: "Well, well, well… look who survived the Challenge.",
    copy: "Respectable. But not enough for a TED Talk.",
    feedback: [
      { threshold: 0.8, line: "Okay prodigy, share it before it cools down." },
      { threshold: 0.5, line: "Respectable chaos control. Do it again." },
      { threshold: 0, line: "Participation trophy unlocked. Proud of you, kinda." },
    ],
    buttons: {
      replay: "Play Again",
      tryAnother: "Try Another Challenge",
      share: "Share Score",
    },
  },
  profile: {
    title: "Pilot profile",
    subtitle: "Stats, streaks, and receipts for your flex.",
    stats: [
      { label: "Challenges played", value: 42, helper: "since Tuesday" },
      { label: "Accuracy", value: "74%", helper: "aim higher" },
      { label: "Current streak", value: "6 wins", helper: "don't blink" },
      { label: "Fastest run", value: "43s", helper: "Fastest Finger" },
    ],
    achievements: [
      { icon: "✨", title: "The Try-Hard Badge", description: "Completed every daily drop for a week." },
      { icon: "💀", title: "10 Wrong Answers in a Row", description: "Committed to the bit. Respect." },
      { icon: "🔥", title: "Fastest Finger in the West", description: "Answered in under 2 seconds. Show-off." },
    ],
  },
  leaderboard: {
    title: "The Hall of Fame (and occasional shame).",
    subtitle: "Flex responsibly. Or don't.",
    filters: ["All Time", "This Week", "Today"],
    fallbackCaption: "Leaderboard is taking a dramatic refresh—enjoy this standby flex.",
  },
};

export const resultShareText = (score) =>
  `I survived Play with ${score} points. Barely.`;
